{{- if .Values.fluxcloud.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flux-chart.fullname" . }}-webhook
  labels:
{{ include "flux-chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "flux-chart.name" . }}-webhook
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
