apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "git2consul.fullname" . }}
  labels:
{{ include "git2consul.labels" . | indent 4 }}
data:
  git2consul.json: |
{{tpl (.Files.Get "git2consul.json") . | indent 4 }}

