apiVersion: v1
kind: Secret
metadata:
  name: {{ include "git2consul.fullname" . }}-ssh
  labels:
{{ include "git2consul.labels" . | indent 4 }}
data:
  config: {{ .Values.git.sshConfig | b64enc | quote }}
  id_rsa: {{ "" | b64enc | quote}}
type: Opaque
