apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: "github"
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "github"
type: Opaque
stringData:
  username: "jasonluck"
  password: ""
  