apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: "nexus-login"
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "nexus-login"
type: Opaque
stringData:
  username: "admin"
  password: "admin123"